version: "3"
services:
  mysql:
    image: docker.io/mysql:latest
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: node-complete
      MYSQL_USER: huynguyen
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306